/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.ssh.domain.Musiclist;
import com.ssh.domain.Musics;
import com.ssh.interfaces.MusicListServiceInterface;
import com.ssh.interfaces.MusicServiceInterface;
import com.ssh.web.form.ListMusicsForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2016
 * 
 * XDoclet definition:
 * @struts.action path="/listmusics" name="listMusicsForm" scope="request" validate="true"
 */
public class ListmusicsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ListMusicsForm listMusicsForm = (ListMusicsForm) form;// TODO Auto-generated method stub
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		MusicServiceInterface msi = (MusicServiceInterface)ctx.getBean("musicservice1");
		MusicListServiceInterface mlsi = (MusicListServiceInterface)ctx.getBean("musiclistservice1");
		Musiclist musiclist = mlsi.getMusiclist(Integer.parseInt(listMusicsForm.getId()));
		List<Musics> list = msi.listMusics(musiclist);
		String listpath = msi.getListpath(musiclist);
		request.setAttribute("musics", list);
		request.setAttribute("path",listpath);
		return mapping.findForward("OK");
	}
}