/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
//import org.springframework.context.ApplicationContext;
//import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.ssh.domain.Users;
import com.ssh.interfaces.UserServiceInterface;
import com.ssh.web.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-14-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="LoginForm" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		//ApplicationContext ac = new ClassPathXmlApplicationContext("applicationContext.xml");
		UserServiceInterface usi = (UserServiceInterface)ctx.getBean("userservice1");
		//UserServiceInterface usi = (UserServiceInterface)ac.getBean("userservice1");
		LoginForm LoginForm = (LoginForm) form;// TODO Auto-generated method stub
		Users user = new Users();
		user.setUsername(LoginForm.getUsername());
		user.setPassword(LoginForm.getPassword());
		user=usi.checkUser(user);
		if(user!=null){
			request.getSession().setAttribute("user", user);
			request.getSession().setAttribute("name", user.getUsername());
			return mapping.findForward("OK");
		}
		else
			return mapping.findForward("ERR");
	
	}
}