/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.ssh.domain.Musiclist;
import com.ssh.interfaces.MusicListServiceInterface;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MusiclistAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		MusicListServiceInterface mlsi = (MusicListServiceInterface)ctx.getBean("musiclistservice1");
		List<Musiclist> list = mlsi.getMusiclists();
		request.getSession().setAttribute("musiclists", list);
		return mapping.findForward("OK");
	}
}