/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.ssh.domain.Global;
import com.ssh.domain.Musics;
import com.ssh.domain.Users;
import com.ssh.interfaces.MusicServiceInterface;
import com.ssh.interfaces.PageServiceInterface;
import com.ssh.web.form.MyMusicForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-15-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MyMusicAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		MyMusicForm mymusicForm = (MyMusicForm) form;
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		Users user = (Users)request.getSession().getAttribute("user");
		MusicServiceInterface msi = (MusicServiceInterface)ctx.getBean("musicservice1");
		List<Musics> list = msi.showMusics(user);
		PageServiceInterface psi = (PageServiceInterface)ctx.getBean("pageservice1");
		list = psi.getPageElements(Integer.parseInt(mymusicForm.getPageid()), Global.mymusicnumber, list);
		if(list.size()!=0){
			request.getSession().setAttribute("mymusic", list);
			return mapping.findForward("OK");
		}
			
		return null;
	}
}