/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.ssh.domain.Musics;
import com.ssh.interfaces.MusicServiceInterface;
import com.ssh.web.form.PlayMymusicForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-19-2016
 * 
 * XDoclet definition:
 * @struts.action path="/playMymusic" name="playMymusicForm" scope="request" validate="true"
 */
public class PlayMymusicAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		PlayMymusicForm playMymusicForm = (PlayMymusicForm) form;// TODO Auto-generated method stub
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		MusicServiceInterface msi = (MusicServiceInterface)ctx.getBean("musicservice1");
		Musics music = new Musics();
		music = msi.getMusic(Integer.parseInt(playMymusicForm.getId()));
		
		request.setAttribute("musicpath", music.getMusicpath());
		return mapping.findForward("OK");
	}
}