/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;




import com.ssh.domain.Singer;
import com.ssh.interfaces.SingerServiceInterface;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SingerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		SingerServiceInterface ssi = (SingerServiceInterface)ctx.getBean("singerservice1");
		List<Singer> list = ssi.getSingers();
		request.getSession().setAttribute("singerlist", list);
		return mapping.findForward("OK");
	}
}